accounts/urls.py
from django.urls import path

from . import views

app_name = "accounts"

urlpatterns = [
    path('profile/edit/', views.profile_edit_redirect, name='profile_edit_redirect'),
    path('profile/<username>/edit/', views.user_profile_edit, name='user_profile_edit'),
    path('profile/<username>/', views.user_profile, name='user_profile'),

]

pages/urls.py
from django.urls import path
from .views import AboutPageView, index

app_name = "pages"

urlpatterns = [
    path('', index, name='index'),
    path('about/', AboutPageView.as_view(), name='about')
]

projects/urls.py
from django.urls import path

from . import views

app_name = "projects"

urlpatterns = [
    path('needs/<needs_filter>/', views.project_listing, name='project_listing'),
    path('new/', views.project_new, name='project_new'),
    path('search/', views.project_search, name='project_search'),
    path('applications/<username>/', views.applications, name='applications'),
    path('<pk>/', views.project_detail, name='project_detail'),
    path('<pk>/edit/', views.project_edit, name='project_edit'),
    path('<pk>/delete/', views.project_delete, name='project_delete'),

]

teambuilder/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static


urlpatterns = [
    # Django Admin
    path('ctrl_77/', admin.site.urls),

    # User management
    path('accounts/', include('allauth.urls')),
    path('accounts/', include('accounts.urls', namespace='accounts')),

    # Local apps
    path('', include('pages.urls', namespace='pages')),
    path('projects/', include('projects.urls', namespace='projects')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from .utils import user_directory_path


class Profile(models.Model):
    """
    Define the Profile Model (linked to the User Model).
    """
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    fullname = models.CharField(max_length=255)
    bio = models.TextField(blank=True)
    avatar = models.ImageField(
        upload_to=user_directory_path,
        max_length=255,
        null=True,
        blank=True,
        default='placeholder/default.jpg',
    )

    def __str__(self):
        return self.fullname


class Skill(models.Model):
    """
    Holds the list of pre-defined and custom skills.
    """
    name = models.CharField(max_length=255)
    type = models.CharField(max_length=1, default='p')  # p (preset) or c (custom).

    def __str__(self):
        return self.name


class UserSkill(models.Model):
    """
    Link the user to one or many skills.
    """
    user = models.ForeignKey(User, related_name='user_skill', on_delete=models.CASCADE)
    skill = models.ForeignKey(Skill, related_name='skill_user', on_delete=models.CASCADE)
    is_skill = models.BooleanField(default=False)


class Portfolio(models.Model):
    """
    Model to hold the user's portfolio links
    (labeled as 'My Projects' in the design).
    """
    user = models.ForeignKey(User, related_name='user_portfolio', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    url = models.URLField()

    def __str__(self):
        return self.name

accounts/forms.py
from allauth.account.forms import SignupForm, LoginForm
from django.contrib.auth.models import User
from django import forms
from django.forms import widgets
from django.forms.formsets import formset_factory
from io import BytesIO as StringIO
from django.core.files.uploadedfile import InMemoryUploadedFile

from PIL import Image

from . import models


class CustomSignUpForm(SignupForm):
    """
    Customise the placeholder text on the SignUp form,
    extending the django allauth form.
    """

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['email'].widget = widgets.TextInput(
            attrs={
                'placeholder': 'Email Address',
            })

        self.fields['password1'].widget = widgets.PasswordInput(
            attrs={
                'placeholder': 'Password',
            })

        self.fields['password2'].widget = widgets.PasswordInput(
            attrs={
                'placeholder': 'Confirm Password',
            })


class CustomLoginForm(LoginForm):
    """
    Customise the placeholder text on the Login form,
    extending the django allauth form.
    """

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['login'].widget = widgets.TextInput(
            attrs={
                'placeholder': 'Email Address',
            })


class ProfileForm(forms.ModelForm):
    """
    Define the Profile Form.
    """

    prefix = 'profile'

    def __init__(self, *args, **kwargs):
        choices = kwargs.pop('choices')
        super(ProfileForm, self).__init__(*args, **kwargs)
        self.fields['skills'].choices = choices

    fullname = forms.CharField(max_length=255, label='')
    bio = forms.CharField(widget=forms.Textarea, label='', required=False)
    skills = forms.MultipleChoiceField(required=False, widget=forms.CheckboxSelectMultiple)

    fullname.widget.attrs.update({
        'class': 'circle--input--h1',
        'placeholder': 'Full Name',
    })

    bio.widget.attrs.update(
        {'placeholder': 'Tell us about yourself...'
         })

    class Meta:
        model = models.Profile
        fields = (
            'fullname',
            'bio',
            'skills',
        )


class CustomSkillsForm(forms.Form):
    """
    Form to capture the custom skills
    added by each user.
    """

    def __init__(self, *args, **kwargs):
        super(CustomSkillsForm, self).__init__(*args, **kwargs)
        self.fields['name'].label = ""

    name = forms.CharField(
        required=False,
        max_length=255,
        widget=forms.TextInput(attrs={
            'placeholder': 'New skill',
        })
    )


# Define the formset for user's Custom Skills
CustomSkillsFormSet = formset_factory(CustomSkillsForm)

#  Define the formset for user's Profile Portfolios (My Projects)
portfolio_inline_formset = forms.inlineformset_factory(
    User,
    models.Portfolio,
    extra=1,
    fields=('name', 'url'),
    widgets={
        'name': forms.TextInput(attrs={'placeholder': 'Project Name'}),
        'url': forms.URLInput(attrs={'placeholder': 'Project URL'}, )}
)


class AvatarForm(forms.ModelForm):
    """
    Capture the user's Avatar data.
    """
    x = forms.FloatField(widget=forms.HiddenInput(), required=False)
    y = forms.FloatField(widget=forms.HiddenInput(), required=False)
    width = forms.FloatField(widget=forms.HiddenInput(), required=False)
    height = forms.FloatField(widget=forms.HiddenInput(), required=False)
    rotate = forms.FloatField(widget=forms.HiddenInput(), required=False)

    class Meta:
        model = models.Profile
        fields = (
            'avatar',
            'x',
            'y',
            'width',
            'height',
            'rotate'
        )
        labels = {
            'avatar': '',
        }
        widgets = {
            'avatar': forms.FileInput(attrs={
                'accept': 'image/*'
            })
        }

    def save(self):
        user = super(AvatarForm, self).save(commit=False)
        x = self.cleaned_data.get('x')
        y = self.cleaned_data.get('y')
        w = self.cleaned_data.get('width')
        h = self.cleaned_data.get('height')
        r = -self.cleaned_data.get('rotate')
        new_size = 400, 400

        pil_image = Image.open(user.avatar)
        rgb_im = pil_image.convert('RGB')
        rotated_image = rgb_im.rotate(r, expand=True)
        cropped_image = rotated_image.crop((x, y, w + x, h + y))
        resized_image = cropped_image.resize(new_size, Image.ANTIALIAS)
        filename = user.avatar.name
        output = StringIO()
        resized_image.save(output, format='JPEG', quality=60)
        output.seek(0)  # Change the stream position to the given byte offset.
        new_image = InMemoryUploadedFile(
            output,
            'ImageField',
            '{}.jpg'.format(filename),
            'image/jpeg',
            output.__sizeof__(),
            None,
        )
        user.avatar = new_image
        user.save()
        return user

accounts/views.py
from django.shortcuts import render
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist, PermissionDenied
from django.urls import reverse
from django.db.models import Q
from django.http import Http404, HttpResponseRedirect
from itertools import chain

from .utils import get_skill_sets, get_saved_skills

from . import forms
from . import models
from projects.models import Project


def user_profile(request, username):
    """
    Show the user profile page
    """
    try:
        profile_user = models.User.objects.get(username=username)
    except ObjectDoesNotExist:
        raise Http404

    profile_user_skills = models.Skill.objects.all().filter(
        skill_user__user=profile_user,
        skill_user__is_skill=True
    ).extra(select={'lower_name': 'lower(name)'}).order_by('lower_name')
    profile_user_portfolios = models.Portfolio.objects.all().filter(
        user_id=profile_user
    )
    profile_projects = Project.objects.prefetch_related('positions').filter(owner=profile_user)
    return render(request, 'accounts/profile.html', {
        'profile_user': profile_user,
        'profile_user_skills': profile_user_skills,
        'profile_user_portfolios': profile_user_portfolios,
        'profile_projects': profile_projects,
    })


@login_required
def profile_edit_redirect(request):
    """
    Redirect the user on first login to
    their profile edit page.
    """
    return HttpResponseRedirect(reverse('accounts:user_profile_edit', args={request.user}))


@login_required
def user_profile_edit(request, username):
    """
    Create and/or edit the User Profile.
    """
    # Get list of custom skills for the current user
    try:
        user_skills = models.Skill.objects.filter(Q(type__exact='c'), skill_user__user_id=request.user)
    except ObjectDoesNotExist:
        raise Http404

    #  Only allow users to edit their own profile
    user = request.user
    if username != user.username:
        raise PermissionDenied

    #  Combine user's custom skills with pre-defined skills into a single choices list
    skills = list(chain(user_skills, models.Skill.objects.all().filter(type__exact='p')))
    choices = [(skill.id, skill.name) for skill in skills]
    choices.sort(key=lambda tup: tup[1].lower())  # Order the list by skill (case insensitive)

    if request.method == 'POST':
        try:
            user.profile = request.user.profile
        except models.Profile.DoesNotExist:
            user.profile = models.Profile(user=request.user)

        profile_form = forms.ProfileForm(
            choices=choices,
            data=request.POST,
            instance=user.profile,
            prefix="profile",
        )

        custom_skills_formset = forms.CustomSkillsFormSet(request.POST, prefix='CSForm')
        dynamic_formset = forms.portfolio_inline_formset(data=request.POST, instance=user, prefix='folio-items')
        avatar_form = forms.AvatarForm(data=request.POST, instance=user.profile, files=request.FILES)

        if (profile_form.is_valid()
                and custom_skills_formset.is_valid()
                and dynamic_formset.is_valid()
                and avatar_form.is_valid()):

            if avatar_form.cleaned_data['x']:
                avatar_form.save()  # only save the avatar if a new image has been uploaded

            user_profile_form = profile_form.save(commit=False)

            # Check which skills should be set to true and which to false
            skill_sets = get_skill_sets(request, profile_form, custom_skills_formset)
            set_to_false = skill_sets[0]
            set_to_true = skill_sets[1]

            #  Update the UserSkill table
            for skill in set_to_false:
                models.UserSkill.objects.filter(user_id=request.user.id, skill_id=skill).update(is_skill=False)
            for skill in set_to_true:
                try:
                    existing = models.UserSkill.objects.get(user_id=request.user.id, skill_id=skill)
                    if not existing.is_skill:
                        models.UserSkill.objects.filter(user_id=request.user.id, skill_id=skill).update(is_skill=True)
                except ObjectDoesNotExist:
                    models.UserSkill.objects.create(user_id=request.user.id, skill_id=skill, is_skill=True)

            user_profile_form.save()
            dynamic_formset.save()

            messages.success(
                request,
                "Profile saved successfully."
            )
            return HttpResponseRedirect(reverse('accounts:user_profile', args={username}))
    else:
        try:   # edit existing user
            fullname = user.profile.fullname
            bio = user.profile.bio
            saved_skills = get_saved_skills(user)

            profile_form = forms.ProfileForm(
                prefix='profile',
                choices=choices,
                initial={
                    'fullname': fullname,
                    'bio': bio,
                    'skills': saved_skills,
                },
            )

        except ObjectDoesNotExist:  # new user
            profile_form = forms.ProfileForm(prefix='profile', choices=choices)

    custom_skills_formset = forms.CustomSkillsFormSet(prefix='CSForm')
    avatar_form = forms.AvatarForm()
    dynamic_formset = forms.portfolio_inline_formset(instance=user, prefix='folio-items')
    profile_projects = Project.objects.prefetch_related('positions').filter(owner=user)

    return render(request, 'accounts/profile_edit.html', {
        'current_user': request.user,
        'profile_form': profile_form,
        'avatar_form': avatar_form,
        'custom_skills_formset': custom_skills_formset,
        'dynamic_formset': dynamic_formset,
        'profile_projects': profile_projects,
    })

accounts/templates/accounts/image_editor_modal.html
<!-- MODAL TO CROP THE IMAGE -->
<div class="modal fade" id="modalCrop">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="modal-title">Image Editor</h3>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true" class="far fa-window-close close-icon"></span>
                </button>
            </div>
            <div class="modal-body">
                <div>
                    <img src="" id="image" style="max-width: 100%;">
                </div>
            </div>
            <div class="p-3">
                <div class="btn-group-lg float-left" role="group" aria-label="Toolbar">
                    <button type="button" class="toolbar-icons js-zoom-in">
                        <span class="fas fa-search-plus img-icons" title="Zoom In"></span>
                    </button>
                    <button type="button" class="toolbar-icons js-zoom-out">
                        <span class="fas fa-search-minus img-icons" title="Zoom Out"></span>
                    </button>
                    <button type="button" class="toolbar-icons js-drag">
                        <span class="fas fa-arrows-alt img-icons" title="Move"></span>
                    </button>
                    <button type="button" class="toolbar-icons js-rotate-counter-clockwise">
                        <span class="fas fa-undo img-icons" title="Rotate Counter-Clockwise"></span>
                    </button>
                    <button type="button" class="toolbar-icons js-rotate-clockwise">
                        <span class="fas fa-undo img-icons flip" title="Rotate Clockwise"></span>
                    </button>
                </div>
                <div class="btn-group-lg float-right" role="group" aria-label="Toolbar-Save">
                    <button type="button"
                            class="button button-secondary btn-sm px-4 py-2 mt-2 e-button sudo_btn"
                            data-dismiss="modal">Cancel
                    </button>
                    <button type="button"
                            class="button button-primary btn-sm px-4 py-2 mt-2 e-button sudo_btn js-crop-and-upload">
                        Save
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>

accounts/templates/accounts/profile.html
{% extends "_base.html" %}
{% load account %}
{% load account_extras %}
{% load static %}
{% block title %} {{ block.super }} | Profile {% endblock %}
{% block body %}

    {% if profile_user == request.user %}
        <div class="circle--actions--bar">
            <nav class="bounds">
                <ul class="circle--pill--list">
                    <li>
                        <a href="{% url 'projects:applications' username=profile_user %}?{% query_str request s='123' %}">Applications</a>
                    </li>
                    <li><a class="selected" href="{% url "accounts:user_profile" username=profile_user %}">Profile</a>
                    </li>
                </ul>
            </nav>
        </div>
    {% endif %}

    <div class="bounds circle--page">
        {% include "messages.html" %}

        <div class="circle--page--header circle--fluid">
            <div class="circle--fluid--cell circle--fluid--primary">
               <h1>{{ profile_user.profile.fullname }}</h1>
            </div>
            <div class="circle--fluid--cell circle--fluid--secondary">
                {% if user == profile_user %}
                    <a class="button icon-on-left space_tp" href="{% url "accounts:user_profile_edit" username=user %}">Edit profile</a>
                    <a class="button icon-on-left space_tp" href="{% url 'account_change_password' %}">Change password</a>
                {% endif %}
            </div>
        </div>
        <div class="grid-70">
            <h2>Profile</h2>
            <div class="circle--article--body">
                <p>{{ profile_user.profile.bio|markdown_to_html }}</p>
            </div>


            <h2>Past Projects</h2>
            <table class="u-full-width circle--table">
                <thead>
                <tr>
                    <th>Project Title</th>
                    <th class="circle--cell--right pl-5">Project Needs</th>
                </tr>
                </thead>

                {% if profile_projects %}
                    {% for project in profile_projects %}
                        <tbody>

                        <tr class="clickable-row" data-href="{% url 'projects:project_detail' pk=project.pk %}">
                            <td class="project_title">
                                <h3>{{ project.title }}</h3>
                            </td>

                            <td class="circle--cell--right">
                                {% for position in project.positions.all %}
                                    <ul>
                                        <li class="secondary-label no-bullets pl-5">{{ position }}</li>
                                    </ul>
                                {% endfor %}
                            </td>
                        </tr>
                    {% endfor %}
                {% endif %}
                </tbody>
            </table>

        </div>

        <div class="grid-25 grid-push-5">
            <div class="circle--secondary--module">
                <div class="circle--primary--avatar">
                    {% if not profile_user.profile.avatar.url %}
                        <img src="{% static 'images/placeholder/default.jpg' %}" class="avatar"
                             alt="Default Avatar">
                    {% else %}
                        <img src="{{ profile_user.profile.avatar.url }}"
                             alt="{{ profile_user.profile.fullname }}" class="avatar">
                    {% endif %}
                </div>
            </div>

            <div class="circle--secondary--module">
                <h4>My Skills</h4>
                {% if profile_user_skills %}
                    <ul class="unloaded">
                        {% for skill in profile_user_skills %}
                            <li>{{ skill }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
            </div>

            <div class="circle--secondary--module">
                <h4>My Projects</h4>
                {% if profile_user_portfolios %}
                    <ul class="circle--link--list">
                        {% for portfolio in profile_user_portfolios %}
                            <li><a href="{{ portfolio.url }}" target="_blank">{{ portfolio }}</a></li>
                        {% endfor %}
                    </ul>
                {% endif %}
            </div>
        </div>
{% endblock %}

accounts/templates/accounts/profile_edit.html
{% extends "_base.html" %}
{% load static %}
{% load account_extras %}
{% block extrahead %}
    <link rel="stylesheet" href="{% static "css/cropper.min.css" %}">
    <script type="text/javascript">
        $(function () {
            $('#custom-skills-forms').formset({
                prefix: "{{ custom_skills_formset.prefix }}",
                addText: 'Add Skill',
                deleteText: 'Remove',
                addCssClass: "circle--clone--add",
                deleteCssClass: "circle--clone--remove",
                formCssClass: "circle--clone--list--custom--skills",
            });
            $('#portfolio_dynamic_formset  p').formset({
                prefix: 'folio-items',
                addText: 'Add Project',
                deleteText: 'Remove',
                addCssClass: "circle--clone--add",
                deleteCssClass: "circle--clone--remove",
                formCssClass: "portfolio-forms",
            });
        });
    </script>
{% endblock %}
{% block title %} {{ block.super }} | Edit Profile {% endblock %}
{% block body %}
    <div class="circle--actions--bar">
        <nav class="bounds">
            <ul class="circle--pill--list">
                <li><a href="{% url 'projects:applications' username=user %}?{% query_str request s='123' %}">Applications</a></li>
                <li><a class="selected" href="{% url "accounts:user_profile" username=user %}">Profile</a></li>
            </ul>
        </nav>
    </div>

    {% include "messages.html" %}

    <div class="bounds circle--page">
        <form method="POST" enctype="multipart/form-data" id="formUpload" action=""
        ">
        <div class="circle--page--header circle--fluid">
            <div class="circle--fluid--cell circle--fluid--primary">
                <h2>Edit profile</h2>
            </div>

            <div class="circle--fluid--cell circle--fluid--secondary">
                <input type="submit" name="update_profile" class="button-primary" value="Save Changes">
            </div>
        </div>

        <div class="grid-70">
            {% csrf_token %}
            {{ profile_form.fullname }}
            {{ profile_form.bio }}
            <p class="help_text">
                <a href="https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet" target="_blank">
                    Markdown is accepted</a></p>
            <div class="circle--article--body">
            </div>
            <h2>Past Projects</h2>
            <table class="u-full-width circle--table">
                <thead>
                <tr>
                    <th>Project Title</th>
                    <th class="circle--cell--right">Project Needs</th>
                </tr>
                </thead>
                <tbody>
                {% for project in profile_projects %}
                    <tr class="clickable-row" data-href="{% url 'projects:project_detail' pk=project.pk %}">
                        <td class="project_title">
                            <h3>{{ project.title }}</h3>
                        </td>

                        <td class="circle--cell--right">
                            {% for position in project.positions.all %}
                                <ul>
                                    <li class="secondary-label no-bullets">{{ position }}</li>
                                </ul>
                            {% endfor %}
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>

        </div>
        <div class="grid-25 grid-push-5">

            <div class="circle--secondary--module">
                <div class="circle--primary--avatar">

                    {% if not current_user.profile.avatar.url %}
                        <img src="{% static 'images/placeholder/default.jpg' %}" class="avatar_editing"
                             alt="Default Avatar">
                    {% endif %}
                    <img src="{{ current_user.profile.avatar.url }}"
                         alt="{{ current_user.profile.fullname }}" class="avatar_editing">
{#                        {{ avatar_form }}#}
                    {{ avatar_form.non_field_errors }}
                    {% for hidden_field in avatar_form.hidden_fields %}
                        {{ hidden_field.errors }}
                        {{ hidden_field }}
                    {% endfor %}
                    <div class="button">
                        <span>Upload Photo</span>
                        <input id="id_avatar" type="file" name="avatar" accept="image/*" class="upload">
                    </div>

                </div>
            </div>
            {% include "accounts/image_editor_modal.html" %}
            <div class="circle--secondary--module">
                <h4>My Skills</h4>
                {% for checkbox in profile_form.skills %}
                    <div>
                        {{ checkbox }}
                    </div>
                {% endfor %}

                <div class="circle--clone--list">
                    <div id="custom-skills-forms">
                        {% for form in custom_skills_formset %}
                            <div id="{{ form.prefix }}-row">
                                {{ form }}
                            </div>
                        {% endfor %}
                    </div>
                </div>

                {{ custom_skills_formset.management_form }}

            </div>

            <div class="circle--secondary--module">
                <h4>My Projects</h4>

                <div class="circle--clone--list">
                    <div id="portfolio_dynamic_formset">
                        {% for portfolio_form in dynamic_formset %}
                            <p>{{ portfolio_form }}</p>
                        {% endfor %}

                    </div>
                </div>
                {{ dynamic_formset.management_form }}

                </form>
            </div>
{% endblock %}