accounts/urls.py
from django.urls import path

from . import views

app_name = "accounts"

urlpatterns = [
    path('profile/edit/', views.profile_edit_redirect, name='profile_edit_redirect'),
    path('profile/<username>/edit/', views.user_profile_edit, name='user_profile_edit'),
    path('profile/<username>/', views.user_profile, name='user_profile'),

]

pages/urls.py
from django.urls import path
from .views import AboutPageView, index

app_name = "pages"

urlpatterns = [
    path('', index, name='index'),
    path('about/', AboutPageView.as_view(), name='about')
]

projects/urls.py
from django.urls import path

from . import views

app_name = "projects"

urlpatterns = [
    path('needs/<needs_filter>/', views.project_listing, name='project_listing'),
    path('new/', views.project_new, name='project_new'),
    path('search/', views.project_search, name='project_search'),
    path('applications/<username>/', views.applications, name='applications'),
    path('<pk>/', views.project_detail, name='project_detail'),
    path('<pk>/edit/', views.project_edit, name='project_edit'),
    path('<pk>/delete/', views.project_delete, name='project_delete'),

]

teambuilder/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static


urlpatterns = [
    # Django Admin
    path('ctrl_77/', admin.site.urls),

    # User management
    path('accounts/', include('allauth.urls')),
    path('accounts/', include('accounts.urls', namespace='accounts')),

    # Local apps
    path('', include('pages.urls', namespace='pages')),
    path('projects/', include('projects.urls', namespace='projects')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

projects/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

from accounts.models import Skill


class Project(models.Model):
    """"
    Model to hold the Project data.
    """
    owner = models.ForeignKey(User, related_name='owner_project', on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    timeline = models.TextField(blank=True)
    requirements = models.TextField(blank=True)
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title


class Position(models.Model):
    """
    Holds the positions linked to projects.
    """
    project = models.ForeignKey(Project, related_name='positions', on_delete=models.CASCADE)
    title = models.CharField(max_length=255, blank=True)
    description = models.TextField(blank=True)
    key_skill = models.ForeignKey(Skill, related_name='key_skill',
                                  help_text='Choose a key skill for this position', on_delete=models.CASCADE)
    filled = models.BooleanField(default=False)

    def __str__(self):
        return self.title


class UserApplication(models.Model):
    """
    Holds the applications for each position.
    Status can be:
    1 - undecided
    2 - approved
    3 - rejected

    """
    user = models.ForeignKey(User, related_name='application_user', on_delete=models.CASCADE)
    position = models.ForeignKey(Position, related_name='application_position', on_delete=models.CASCADE)
    status = models.IntegerField(default=1)
    created_at = models.DateTimeField(default=timezone.now)

projects/forms.py
from django import forms

from . import models


class ProjectForm(forms.ModelForm):
    """
    Define the Profile Form
    """

    prefix = 'project'

    title = forms.CharField(max_length=255, label='')
    description = forms.CharField(widget=forms.Textarea, label='', required=False)
    timeline = forms.CharField(widget=forms.Textarea, label='', required=False)
    requirements = forms.CharField(widget=forms.Textarea, label='', required=False)

    class Meta:
        model = models.Project
        fields = (
            'title',
            'description',
            'timeline',
            'requirements'
        )

    title.widget.attrs.update({
        'class': 'circle--input--h1',
        'placeholder': 'Project Title',
    })

    description.widget.attrs.update({
        'class': 'generic-textarea',
        'placeholder': 'Project description...'
    })

    timeline.widget.attrs.update({
        'class': 'circle--textarea--input',
        'placeholder': 'Time estimate',
    })

    requirements.widget.attrs.update({
        'class': 'circle--textarea--input',
    })


class BaseArticleFormset(forms.BaseInlineFormSet):
    def clean(self):
        """
        Checks that no two positions have the same title.
        """
        if any(self.errors):
            return
        titles = []
        for form in self.forms:
            if self.can_delete and self._should_delete_form(form):
                continue

            title = form.cleaned_data.get('title')
            title = str(title).lower()
            if str(title).lower() in titles:
                raise forms.ValidationError("Error: positions on a project must have distinct titles.")
            titles.append(title)

            key_skill = form.cleaned_data.get('key_skill')
            if key_skill and not title:
                raise forms.ValidationError("Error: enter a title for this position.")


#  Define the formset for Positions attached to a Project
position_inline_formset = forms.inlineformset_factory(
    models.Project,
    models.Position,
    formset=BaseArticleFormset,
    extra=1,
    fields=('title', 'description', 'key_skill'),
    widgets={
        'title': forms.TextInput(attrs={'placeholder': 'Position Title', 'class': 'circle--input--h3'}),
        'description': forms.Textarea(attrs={'placeholder': 'Position description...'},),
        'key_skill': forms.Select(attrs={'class': 'skill_selector'}),
    },
)


class DeleteProjectForm(forms.Form):
    class Meta:
        fields = ('title',)


class ApplicationForm(forms.ModelForm):
    class Meta:
        model = models.UserApplication
        fields = (
            'position',
        )


class AcceptApplicationForm(forms.Form):
    applicant = forms.CharField()
    position = forms.CharField()

    class Meta:
        fields = (
            'applicant,'
            'position',
        )

projects/views.py
from django.core.exceptions import ObjectDoesNotExist, PermissionDenied
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import Http404, HttpResponseRedirect
from django.urls import reverse
from django.db.models import Q

from .utils import (get_slugified_list, get_search_term, get_project_needs,
                    send_application_received_mail, send_application_result_mail)
from . import forms
from . import models
from accounts.models import Skill, UserSkill


def project_listing(request, needs_filter):
    """
    Return the filtered list of Projects
    based on Project Needs.
    """
    all_projects = models.Project.objects.prefetch_related('positions').order_by('-created_at')
    num_projects = filtered_num_projects = len(all_projects)
    project_needs = get_project_needs(all_projects)

    if needs_filter == 'all':
        projects = all_projects
        search_term = 'all'
    elif needs_filter == 'suggested':
        if request.user.is_authenticated:
            user_skills = UserSkill.objects.filter(
                Q(user_id=request.user) &
                Q(is_skill=True))
            user_skillset = [skill.skill_id for skill in user_skills]
            projects = set(all_projects.order_by('-created_at').filter(
                Q(positions__key_skill__in=user_skillset) &
                Q(positions__filled=False) &
                ~Q(owner__exact=request.user)))
            search_term = 'suggested'
            filtered_num_projects = len(projects)
            totals = (num_projects, filtered_num_projects)
        else:
            raise PermissionDenied
    else:
        search_term = get_search_term(needs_filter, project_needs)
        projects = all_projects.order_by('-created_at').filter(positions__title=search_term)
        filtered_num_projects = len(projects)
    totals = (num_projects, filtered_num_projects)

    return render(request, 'projects/project_listing.html', {
        'projects': projects,
        'project_needs': project_needs,
        'search_term': search_term,
        'totals': totals,
    })


@login_required
def project_new(request):
    """
    Create a new Project
    and associated Positions.
    """
    if request.method == 'POST':
        user = request.user
        user.project = models.Project(owner=request.user)
        project_form = forms.ProjectForm(data=request.POST, instance=user.project)
        positions_formset = forms.position_inline_formset(
            data=request.POST,
            instance=user.project,
            prefix='position-items'
        )

        if project_form.is_valid() and positions_formset.is_valid():
            project = project_form.save()
            positions_formset.save()
            messages.success(request, "Project created successfully.")
            return redirect('projects:project_detail', pk=project.pk)
    else:
        project_form = forms.ProjectForm()
        positions_formset = forms.position_inline_formset(prefix='position-items',)

    return render(request, 'projects/project_new_edit.html', {
        'mode': 'create',
        'project_form': project_form,
        'positions_formset': positions_formset,
    })


@login_required
def project_edit(request, pk):
    """
    Edit a Project
    and associated Positions.
    """
    try:
        project = models.Project.objects.select_related(
            'owner__profile'
        ).prefetch_related(
            'positions__application_position__user'
        ).get(
            id=pk
        )
    except ObjectDoesNotExist:
        raise Http404

    #  Only allow users to edit their own projects
    if request.user != project.owner:
        raise PermissionDenied

    if request.method == 'POST':
        project_form = forms.ProjectForm(data=request.POST, instance=project)
        positions_formset = forms.position_inline_formset(
            data=request.POST,
            instance=project,
            prefix='position-items'
        )

        if project_form.is_valid() and positions_formset.is_valid():
            project = project_form.save()
            positions_formset.save()
            messages.success(request, "Project updated successfully.")
            return redirect('projects:project_detail', pk=project.pk)
    else:
        project_form = forms.ProjectForm(instance=project)
        positions_formset = forms.position_inline_formset(instance=project, prefix='position-items')

    return render(request, 'projects/project_new_edit.html', {
        'pk': pk,
        'mode': 'edit',
        'project_form': project_form,
        'positions_formset': positions_formset,
    })


@login_required
def project_detail(request, pk):
    """
    Show the project detail page.
    """
    try:
        project = models.Project.objects.select_related(
            'owner__profile',
        ).prefetch_related(
            'positions__application_position__user'
        ).get(
            id=pk
        )
    except ObjectDoesNotExist:
        raise Http404

    if request.method == 'POST':
        application_form = forms.ApplicationForm(data=request.POST)
        if application_form.is_valid():
            application = application_form.save(commit=False)
            position = application_form.cleaned_data['position']
            application.user = request.user
            application.save()
            messages.success(request, "Application received.")
            send_application_received_mail(
                email_to=application.user.email,
                name=application.user.profile.fullname,
                position=position,
                project=project
            )
            return render(request, 'projects/application_confirm.html', {
                'position': position,
            })

    else:
        application_form = forms.ApplicationForm()

    return render(request, 'projects/project_detail.html', {
        'project': project,
        'application_form': application_form,
    })


@login_required
def project_delete(request, pk):
    """
    Delete the Project.
    """
    try:
        project = models.Project.objects.get(id=pk)
    except ObjectDoesNotExist:
        raise Http404

    #  Only allow users to edit their own projects
    if request.user != project.owner:
        raise PermissionDenied

    if request.method == 'POST':
        delete_form = forms.DeleteProjectForm(data=request.POST)
        if delete_form.is_valid():
            project.delete()
            messages.success(
                request,
                "Project deleted successfully."
            )
            return HttpResponseRedirect(reverse('projects:project_listing', args={'all'}))
    else:
        delete_form = forms.DeleteProjectForm()

    return render(request, 'projects/project_delete.html', {
        'project': project,
        'delete_form': delete_form,
    })


def project_search(request):
    """
    Search Project based on words in
    their title or description.
    """
    term = request.GET.get('q')
    projects = models.Project.objects.prefetch_related('positions').order_by('-created_at')
    project_needs = get_project_needs(projects)
    search_term = 'all'
    search_results = projects.filter(
        Q(title__icontains=term) |
        Q(description__icontains=term)
    )
    num_results = len(search_results)

    return render(request, 'projects/project_search.html', {
        'projects': projects,
        'project_needs': project_needs,
        'term': term,
        'search_results': search_results,
        'num_results': num_results,
        'search_term': search_term,
    })


@login_required
def applications(request, username):
    #  Get the user based on the supplied username
    try:
        profile_user = models.User.objects.get(username=username)
    except ObjectDoesNotExist:
        raise Http404

    #  Only allow users to view their own applications page
    if request.user != profile_user:
        raise PermissionDenied

    #  Retrieve the URL query strings (set to 'all' or '123' if not supplied)
    status = request.GET.get('s', '123')
    proj = request.GET.get('p', 'all')
    need = request.GET.get('n', 'all')
    m_status = [status, proj, need]

    #  Get all the projects owned by the user
    all_user_projects = models.Project.objects.all().prefetch_related('positions').filter(owner=profile_user)

    # Make a (slugified, Display Name) list of the user's projects
    project_list = get_slugified_list(all_user_projects)

    # Make a (slugified, Display Name) list of project needs associated with the user's projects
    project_needs = get_project_needs(all_user_projects)

    # Get the search term based on the slugified term supplied in the URL query string
    proj_term = get_search_term(proj, project_list)
    need_term = get_search_term(need, project_needs)

    # Set defaults and identify the search type (1 to 4)
    # filter the all_user_projects queryset accordingly
    search_type = 1
    # user_projects = all_user_projects

    #  All Projects and all Needs
    if proj == 'all' and need == 'all':
        search_type = 1
        user_projects = all_user_projects

    #  All Needs, filtered Projects
    elif need == 'all' and proj != 'all':
        search_type = 2
        user_projects = all_user_projects.filter(title=proj_term)

    #  All Projects, filtered Needs
    elif need != 'all' and proj == 'all':
        search_type = 3
        user_projects = all_user_projects.filter(positions__title__exact=need_term)

    # Filters Projects and filtered Needs
    elif proj != 'all' and need != 'all':
        search_type = 4
        user_projects = all_user_projects.filter(
            Q(title=proj_term) &
            Q(positions__title=need_term))

    #  Get all the applications on projects owned by the user
    user_applications = models.UserApplication.objects.filter(position__project__owner=request.user)

projects/templates/projects/application_confirm.html
{% extends '_base.html' %}
{% load static %}
{% block title %} {{ block.super }} | Application Confirmation{% endblock %}
{% block body %}
    <div class="bounds circle--page">
        {% include "messages.html" %}
        <div class="container">
            <div class="bounds">
                {%  if position %}
                <h1>Application received</h1>
                <p>Thank you for your application for the role of <span class="secondary-label">{{ position }}</span>.</p>
                    <p>You will receive an email confirmation shortly.</p>
                {% else %}
                <h1>Application updated</h1>
                <p>The applicant(s) will be notified of your decision via email.</p>
                {% endif %}
                <a class="button button-primary" href="{% url 'projects:project_listing' needs_filter='all' %}">Continue</a>
            </div>
        </div>
    </div>
{% endblock %}

projects/templates/projects/applications.html
{% extends '_base.html' %}
{% load static %}
{% load project_extras %}
{% block title %} {{ block.super }} | Applications{% endblock %}
{% block body %}

    {% if profile_user == request.user %}
        <div class="circle--actions--bar">
            <nav class="bounds">
                <ul class="circle--pill--list">
                    <li><a class="selected"
                           href="{% url 'projects:applications' username=profile_user %}?{% query_str request s='123' %}">Applications</a>
                    </li>
                    <li><a href="{% url "accounts:user_profile" username=profile_user %}">Profile</a></li>
                </ul>
            </nav>
        </div>
    {% endif %}

    <div class="bounds circle--page">
        {% include "messages.html" %}

        <div class="circle--page--header grid-100">
            <h2>Applications</h2>
                <div class="mt-1"><span class="secondary-label">{{ totals.1 }} selected / {{ totals.0 }} total</span>
                </div>
        </div>

        <div class="grid-25">
            <div class="circle--filter circle--secondary--module">
                <h4>Status</h4>
                <ul class="circle--filter--list">
                    <li>
                        <a href="{% url 'projects:applications' username=profile_user %}?{% query_str request s='123' %}"
                           {% if m_status.0 == '123'%}class="selected"{% endif %}>All Applications</a>
                    </li>
                    <li>
                        <a href="{% url 'projects:applications' username=profile_user %}?{% query_str request s=1 %}"
                           {% if m_status.0 == '1' %}class="selected"{% endif %}>New Applications</a>
                    </li>
                    <li>
                        <a href="{% url 'projects:applications' username=profile_user %}?{% query_str request s=2 %}"
                           {% if m_status.0 == '2' %}class="selected"{% endif %}>Accepted</a>
                    </li>
                    <li>
                        <a href="{% url 'projects:applications' username=profile_user %}?{% query_str request s=3 %}"
                           {% if m_status.0 == '3' %}class="selected"{% endif %}>Rejected</a>
                    </li>
                </ul>
            </div>

            <div class="circle--filter circle--secondary--module">
                <h4>My Projects</h4>
                <ul class="circle--filter--list">
                    {% for slug, project in project_list %}
                        <li>
                            <a href="{% url 'projects:applications' username=profile_user %}?{% query_str request p=slug %}"
                               {% if  m_status.1 == slug %}class="selected"{% endif %}>{{ project }}</a>
                        </li>
                    {% endfor %}
                </ul>
            </div>

            <div class="circle--filter circle--secondary--module">
                <h4>Project Needs</h4>
                <ul class="circle--filter--list">
                    {% for slug, position in project_needs %}
                        <li>
                            <a href="{% url 'projects:applications' username=profile_user %}?{% query_str request n=slug %}"
                            {% if  m_status.2 == slug %}class="selected"{% endif %}>{{ position }}</a>
                        </li>
                    {% endfor %}
                </ul>
            </div>

        </div>

        <div class="grid-70 grid-push-5">
            <table class="u-full-width circle--table">
                <thead>
                <tr>
                    <th>Applicant</th>
                    <th>Applicant Position</th>
                    <th class="circle--cell--right">Status</th>
                </tr>
                </thead>
                {% if not all_applications %}
                    <tbody>
                    <tr>
                        <td><span class="red_text">No applications</span></td>
                        <td></td>
                        <td></td>
                    </tr>
                    </tbody>
                {% else %}
                    {% for application in all_applications %}
                        <tbody>
                        <tr class="clickable-row"
                            data-href="{% url 'accounts:user_profile' username=application.user %}">
                            <td>
                                <h3>{{ application.user.profile.fullname }}</h3>
                                <p>{{ application.position.project }}</p>
                            </td>
                            <td>
                                <span class="secondary-label">{{ application.position }}</span>
                            </td>
                            <td class="circle--cell--right">

                                {% if application.status == 2 %}
                                    <span class="btn_accepted">Accepted &#10003;</span>
                                {% elif application.status == 3 %}
                                    <span class="btn_rejected">Rejected &#10007;</span>
                                {% else %}
                                    <form method="POST" name="accept" action="">
                                        {% csrf_token %}
                                        <input type="hidden" name="applicant" id="id_applicant"
                                               value="{{ application.user_id }}">
                                        <input type="hidden" name="position" id="id_position"
                                               value="{{ application.position.id }}">
                                        <input type="submit" name="accept" class="button-primary btn_small"
                                               value="Accept">
                                        <input type="submit" name="reject" class="button btn_small" value="Reject">
                                    </form>
                                {% endif %}
                            </td>
                        </tr>
                        </tbody>
                    {% endfor %}
                {% endif %}
            </table>

        </div>

    </div>
{% endblock %}

projects/templates/projects/project_detail.html
{% extends '_base.html' %}
{% load static %}
{% load project_extras %}
{% block title %} {{ block.super }} | Project Detail {% endblock %}
{% block body %}

    {% if user == project.owner %}
        <div class="circle--actions--bar">
            <div class="bounds">
                <div class="grid-100">
                    <a class="button" href="{% url 'projects:project_edit' pk=project.id %}">Edit Project</a>
                    <a class="button button-text" href="{% url 'projects:project_delete' pk=project.id %}">Delete
                        Project</a>
                </div>
            </div>
        </div>
    {% endif %}
    <div class="bounds circle--page circle--article">
        {% include "messages.html" %}
        <div class="grid-70">
            <div class="circle--article--header">
                <h4 class="circle--article--section">Project</h4>
                <h1 class="circle--article--title">{{ project.title }}</h1>
                <p class="circle--article--byline">
                    Project Owner:
                    <a href="{% url 'accounts:user_profile' username=project.owner %}">{{ project.owner.profile }}</a>
                </p>
            </div>

            <div class="circle--article--body">
                {{ project.description|markdown_to_html }}
            </div>

            <div class="circle--project--positions">
                <h2>Positions</h2>
                <ul class="circle--group--list">
                    {% for position in project.positions.all %}
                        <li>
                            <h3>{{ position.title }}</h3>
                            <p>{{ position.description|markdown_to_html }}</p>
                            <h5>Key Skill:</h5>
                            <div class="secondary-label pb-4">{{ position.key_skill }}</div>
                            {% if position.filled %}
                                <a class="button button-primary button-inactive">Position Filled</a>
                            {% else %}
                                {% if user != project.owner %}
                                    {% if position.application_position.all|check_application_status:user %}
                                        <a class="button button-primary button-inactive">You have applied for this
                                            position</a>
                                    {% else %}
                                        <form method="POST"
                                              action="{% url 'projects:project_detail' pk=project.pk %}">
                                            {% csrf_token %}
                                            <input type="hidden" name="position" id="id_position"
                                                   value="{{ position.id }}">
                                            <input type="submit" name="application" class="button-primary"
                                                   value="Apply">
                                        </form>
                                    {% endif %}
                                {% endif %}
                            {% endif %}
                        </li>
                    {% endfor %}
                </ul>
            </div>

        </div>

        <div class="grid-25 grid-push-5">
            <div class="circle--secondary--module">
                <h3>Project Needs</h3>
                <ul class="circle--link--list">
                    {% for project in project.positions.all %}
                        <li><a href="#">{{ project.title }}</a></li>
                    {% endfor %}
                </ul>
            </div>

            <div class="circle--secondary--module">
                <h3>Project Timeline</h3>
                <p>{{ project.timeline }}</p>
            </div>

            <div class="circle--secondary--module">
                <h3>Applicant Requirements</h3>
                <p>{{ project.requirements }}</p>
            </div>

        </div>
    </div>
{% endblock %}

projects/templates/projects/project_new_edit.html
{% extends '_base.html' %}
{% load static %}
{% block title %}
    {{ block.super }} {% if mode == 'create' %}| New Project {% else %} | Edit Project {% endif %}
{% endblock %}
{% block extrahead %}
    <script type="text/javascript">
        $(function () {
            $('#positions_formset  li').formset({
                prefix: 'position-items',
                addText: 'Add Position',
                deleteText: 'Remove',
                addCssClass: "circle--clone--add",
                deleteCssClass: "circle--clone--remove",
                formCssClass: "position-forms"
            });
        });
    </script>
{% endblock %}
{% block body %}
    {% if mode == 'create' %}
        <form method="POST" action="{% url 'projects:project_new' %}">
    {% elif mode == 'edit' %}
        <form method="POST" action="{% url 'projects:project_edit' pk=pk %}">
    {% endif %}
<div class="circle--actions--bar">
    <div class="bounds">
        {% if mode == 'create' %}
            <div class="grid-100">
                <input type="submit" name="save_changes" class="button-primary mb-0" value="Save Project">
                <a class="button button-text" href="{% url 'projects:project_listing' needs_filter='all' %}">Discard</a>
            </div>
        {% elif mode == 'edit' %}
            <div class="grid-100">
                <input type="submit" name="save_changes" class="button-primary mb-0" value="Save Changes">
                <a class="button button-text" href="{% url 'projects:project_delete' pk=pk %}">Delete Project</a>
            </div>
        {% endif %}

    </div>
</div>
<div class="bounds circle--page">
    {% include "messages.html" %}
    <div class="bounds circle--page circle--article">
        <div class="grid-70">
            {% csrf_token %}
            <div class="circle--article--body">
                {{ project_form.title }}
                {{ project_form.description }}
                <p class="help_text">
                    <a href="https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet" target="_blank">
                        Markdown is accepted</a></p>
            </div>

            <div class="circle--project--positions">
                <h2>Positions</h2>
                <ul class="circle--group--list circle--clone--list" id="positions_formset">
                    {% for position_form in positions_formset %}
                        <li>{{ position_form }}
                            {% if position_form.key_skill.errors %}
                                <div class="error_red">{{ position_form.key_skill.errors.as_text|escape }}</div>
                            {% endif %}
                        </li>
                    {% endfor %}
                </ul>
            </div>
            {% if positions_formset.non_form_errors %}
                <div class="error_red">
                    <span>
                        {% for error in positions_formset.non_form_errors %}
                            {{ error }}
                        {% endfor %}
                    </span>
                </div>
            {% endif %}
            {{ positions_formset.management_form }}
            <input type="submit" name="save_changes" class="button-primary" value="Save Changes">
        </div>



    <div class="grid-25 grid-push-5">

        <div class="circle--secondary--module">
            <h3>Project Timeline</h3>
            {{ project_form.timeline }}
        </div>

        <div class="circle--secondary--module">
            <h3>Applicant Requirements</h3>
            {{ project_form.requirements }}
        </div>
    </div>

</div>

</div>
</form>
{% endblock %}