accounts/urls.py
from django.urls import path

from . import views

app_name = "accounts"

urlpatterns = [
    path('profile/edit/', views.profile_edit_redirect, name='profile_edit_redirect'),
    path('profile/<username>/edit/', views.user_profile_edit, name='user_profile_edit'),
    path('profile/<username>/', views.user_profile, name='user_profile'),

]

pages/urls.py
from django.urls import path
from .views import AboutPageView, index

app_name = "pages"

urlpatterns = [
    path('', index, name='index'),
    path('about/', AboutPageView.as_view(), name='about')
]

projects/urls.py
from django.urls import path

from . import views

app_name = "projects"

urlpatterns = [
    path('needs/<needs_filter>/', views.project_listing, name='project_listing'),
    path('new/', views.project_new, name='project_new'),
    path('search/', views.project_search, name='project_search'),
    path('applications/<username>/', views.applications, name='applications'),
    path('<pk>/', views.project_detail, name='project_detail'),
    path('<pk>/edit/', views.project_edit, name='project_edit'),
    path('<pk>/delete/', views.project_delete, name='project_delete'),

]

teambuilder/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static


urlpatterns = [
    # Django Admin
    path('ctrl_77/', admin.site.urls),

    # User management
    path('accounts/', include('allauth.urls')),
    path('accounts/', include('accounts.urls', namespace='accounts')),

    # Local apps
    path('', include('pages.urls', namespace='pages')),
    path('projects/', include('projects.urls', namespace='projects')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

templates/_base.html
{% load static %}
{% load account %}
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Basic Page Needs
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <meta charset="utf-8">
    <title>{% block title %}Team Builder{% endblock %}</title>
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Mobile Specific Metas
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- FONTS
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <link href='https://fonts.googleapis.com/css?family=Work+Sans:400,500' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Cousine' rel='stylesheet' type='text/css'>

    <!-- Font Awesome Icons
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <script src="https://kit.fontawesome.com/bd0f673c70.js" crossorigin="anonymous"></script>


    <!-- jQuery & jquery formset
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <script type="text/javascript" src="{% static "js/jquery-3.5.1.min.js" %}"></script>
    <script type="text/javascript" src="{% static "js/jquery.formset.js" %}"></script>

    <!-- Bootstrap CSS & JS
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">
    <script type="text/javascript" src="{% static "js/bootstrap.bundle.min.js" %}"></script>

    <!-- JavaScript
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->

    <script type="text/javascript" src="{% static "js/autogrow.js" %}"></script>
    <script type="text/javascript" src="{% static "js/global.js" %}"></script>


    <!-- jquery cropper
        –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <script type="text/javascript" src="{% static "js/cropper.min.js" %}"></script>
    <script type="text/javascript" src="{% static "js/jquery-cropper.min.js" %}"></script>


    <!-- Global CSS
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <link rel="stylesheet" href="{% static "css/global.css" %}">
    <link rel="stylesheet" href="{% static "css/custom.css" %}">


    <!-- Favicon
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <link rel="shortcut icon" type="image/png" href="{% static 'images/favicon.png' %}">

    {% block extrahead %}{% endblock %}
</head>
<body>
<header class="circle--header">
    <div class="bounds">
        <div class="circle--fluid">
            <div class="circle--fluid--cell">
                <h1 class="hide-text circle--logo">
                    <a class="logo" href="{% url "projects:project_listing" needs_filter='all' %}">Circle</a>
                </h1>
            </div>
            <div class="circle--fluid--cell">
                <nav>
                    {% with url_name=request.resolver_match.url_name %}
                        <ul>
                            <li><a href="{% url "projects:project_listing" needs_filter='all' %}"
                                   {% if url_name == 'project_listing' %}class="active"{% endif %}>Home</a></li>
                            <li><a href="{% url "pages:about" %}"
                                   {% if url_name == 'about' %}class="active"{% endif %}>About</a>
                            </li>
                        </ul>
                    {% endwith %}
                </nav>
            </div>
            <div class="circle--fluid--cell circle--fluid--primary">
                <div class="circle--search">
                    <form action="{% url 'projects:project_search' %}" method="GET" class="search_form">
                        <input type="text" placeholder="Search Projects..." name="q"/>
                        <button>
                            <svg version="1.1" class="search" xmlns="http://www.w3.org/2000/svg"
                                 xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 12 12"
                                 xml:space="preserve">
                <path d="M12,10.6L8.3,6.9C8.7,6.2,9,5.4,9,4.5C9,2,7,0,4.5,0S0,2,0,4.5S2,9,4.5,9c0.9,0,1.7-0.3,2.4-0.7l3.7,3.7L12,10.6z M2,4.5
                C2,3.1,3.1,2,4.5,2S7,3.1,7,4.5C7,5.9,5.9,7,4.5,7S2,5.9,2,4.5z"/>
              </svg>
                        </button>
                    </form>
                </div>
            </div>


            <div class="circle--fluid--cell circle--fluid--secondary">
                <nav>
                    <ul class="circle--inline">
                        {% if not user.is_authenticated %}
                            <li><a href="{% url "account_signup" %}">Sign Up</a></li>
                            <li><a href="{% url "account_login" %}">Sign In</a></li>
                        {% else %}
                            <li>{% if not user.profile.avatar.url %}
                                <a href="{% url "accounts:user_profile" username=user %}"><img
                                        src="{% static 'images/placeholder/default.jpg' %}"
                                        class="avatar_header"
                                        alt="Default Avatar"></a>
                            {% else %}
                                <a href="{% url "accounts:user_profile" username=user %}"><img
                                        src="{{ user.profile.avatar.url }}"
                                        alt="{{ user.profile.fullname }}"
                                        title="{{ user.profile.fullname }}"
                                        class="avatar_header"></a></li>
                            {% endif %}
                            <li><a href="{% url "account_logout" %}">Logout</a></li>
                        {% endif %}
                    </ul>
                </nav>
            </div>
        </div>
    </div>
</header>
{% block body %}{% endblock %}
</body>
</html>

templates/index.html
{% extends '_base.html' %}
{% load static %}
{% block body %}

    <div class="bounds circle--page">
        <div class="circle--page--header circle--fluid">
            <div class="circle--fluid--cell circle--fluid--primary">
                <p>*** you will be redirected ***</p>
            </div>
        </div>
    </div>
{% endblock %}

templates/layout.html
{% load static %}
{% load account %}
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Basic Page Needs
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <meta charset="utf-8">
    <title>{% block title %}Team Builder{% endblock %}</title>
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Mobile Specific Metas
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- FONTS
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <link href='https://fonts.googleapis.com/css?family=Work+Sans:400,500' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Cousine' rel='stylesheet' type='text/css'>

    <!-- Font Awesome Icons
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <script src="https://kit.fontawesome.com/bd0f673c70.js" crossorigin="anonymous"></script>


    <!-- jQuery & jquery formset
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <script type="text/javascript" src="{% static "js/jquery-3.5.1.min.js" %}"></script>
    <script type="text/javascript" src="{% static "js/jquery.formset.js" %}"></script>

    <!-- Bootstrap CSS & JS
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">
    <script type="text/javascript" src="{% static "js/bootstrap.bundle.min.js" %}"></script>

    <!-- JavaScript
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->

    <script type="text/javascript" src="{% static "js/autogrow.js" %}"></script>
    <script type="text/javascript" src="{% static "js/global.js" %}"></script>


    <!-- jquery cropper
        –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <script type="text/javascript" src="{% static "js/cropper.min.js" %}"></script>
    <script type="text/javascript" src="{% static "js/jquery-cropper.min.js" %}"></script>


    <!-- Global CSS
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <link rel="stylesheet" href="{% static "css/global.css" %}">
    <link rel="stylesheet" href="{% static "css/custom.css" %}">


    <!-- Favicon
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <link rel="shortcut icon" type="image/png" href="{% static 'images/favicon.png' %}">

    {% block extrahead %}{% endblock %}
</head>
<body>
<header class="circle--header">
    <div class="bounds">
        <div class="circle--fluid">
            <div class="circle--fluid--cell">
                <h1 class="hide-text circle--logo">
                    <a class="logo" href="{% url "projects:project_listing" needs_filter='all' %}">Circle</a>
                </h1>
            </div>
            <div class="circle--fluid--cell">
                <nav>
                    <ul>
                        <li><a href="{% url "projects:project_listing" needs_filter='all' %}">Home</a></li>
                        <li><a href="#">About</a></li>
                    </ul>
                </nav>
            </div>
            <div class="circle--fluid--cell circle--fluid--primary">
                <div class="circle--search">
                    <form action="{% url 'projects:project_search' %}" method="GET" class="search_form">
                        <input type="text" placeholder="Search Projects..." name="q"/>
                        <button>
                            <svg version="1.1" class="search" xmlns="http://www.w3.org/2000/svg"
                                 xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 12 12"
                                 xml:space="preserve">
                <path d="M12,10.6L8.3,6.9C8.7,6.2,9,5.4,9,4.5C9,2,7,0,4.5,0S0,2,0,4.5S2,9,4.5,9c0.9,0,1.7-0.3,2.4-0.7l3.7,3.7L12,10.6z M2,4.5
                C2,3.1,3.1,2,4.5,2S7,3.1,7,4.5C7,5.9,5.9,7,4.5,7S2,5.9,2,4.5z"/>
              </svg>
                        </button>
                    </form>
                </div>
            </div>


            <div class="circle--fluid--cell circle--fluid--secondary">
                <nav>
                    <ul class="circle--inline">
                        {% if not user.is_authenticated %}
                            <li><a href="{% url "account_signup" %}">Sign Up</a></li>
                            <li><a href="{% url "account_login" %}">Sign In</a></li>
                        {% else %}
                            <li>{% if not user.profile.avatar.url %}
                                <a href="{% url "accounts:user_profile" username=user %}"><img
                                        src="{% static 'images/placeholder/default.jpg' %}"
                                        class="avatar_header"
                                        alt="Default Avatar"></a>
                            {% else %}
                                <a href="{% url "accounts:user_profile" username=user %}"><img
                                        src="{{ user.profile.avatar.url }}"
                                        alt="{{ user.profile.fullname }}"
                                        title="{{ user.profile.fullname }}"
                                        class="avatar_header"></a></li>
                            {% endif %}
                            <li><a href="{% url "account_logout" %}">Logout</a></li>
                        {% endif %}
                    </ul>
                </nav>
            </div>
        </div>
    </div>
</header>
{% block body %}{% endblock %}
</body>
</html>

templates/messages.html
<div class="bounds">
    {% if messages %}
        <ul>
            {% for message in messages %}
                <li{% if message.tags %}
                    class="no-bullets alert alert-{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
</div>